name: Publish Workflow

on:
  push:
    branches:
      - main

jobs:
  BuildAndTest:
    runs-on: windows-latest
    name: Run Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
          
      - name: Build and Publish
        run: |  
          dotnet build
          dotnet test

  BuildAndPublish:
    needs: BuildAndTest
    runs-on: windows-latest
    name: Update NuGet 
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
          
      - name: Build and Publish
        run: |  
          cd Nanotek.Helpers
          dotnet nuget add source --username kris701 --password ${{ secrets.API_KEY_GITHUB }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/kris701/index.json"
          dotnet build --configuration Release
          dotnet pack --configuration Release
          cd bin
          cd Release
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_GITHUB }} --source "github" --skip-duplicate
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_NUGET }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
